### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by cdalexndr** [doesdev/rollup-plugin-analyzer#11]
Using the following **rollup.config**:

```
import {analyze} from 'rollup-plugin-analyzer';
export default {
    input: './first.js',
    output: {
        file: 'bundle.js',
        format: 'iife',
        name: 'bundle'
    },
    plugins: [
        analyze({stdout: true})
    ]
};
```

Building with the following command doesn't print the analytics information:
```
> rollup -c .\rollup.config.js

./first.js → bundle.js...
created bundle.js in 31ms
```

Same results without any options passed to plugin.

**Comment by doesdev** [comment]
You'll want to use the default import:

```js
import analyze from 'rollup-plugin-analyzer';
```

That was a change in the 3.0.0 release to be more consistent with other Rollup plugins. 

It can still be required destructured, but not used as a named import. So in a node build script you can still use
```js
const { analyze } = require('rollup-plugin-analyzer');
```
but not 
```js
import { analyze } from 'rollup-plugin-analyzer';
````

**Comment by cdalexndr** [comment]
Same issue with `import analyze from 'rollup-plugin-analyzer'`.
Note that I am not using a node build script, but running from a terminal.

**Comment by doesdev** [comment]
What Rollup version are you using?

**Comment by cdalexndr** [comment]
rollup v1.16.4

**Comment by doesdev** [comment]
Odd, I'm running 1.16.6 and tried your identical config (with the default import) and it worked as expected. Also updated Rollup in the project and ran all tests against it and all passed. 

Are you able to provide a repro gist or repo I could test with?

**Comment by cdalexndr** [comment]
https://github.com/cdalexndr/rollup-plugin-analyzer-bug-11

**Comment by doesdev** [comment]
Worked for me on Windows CMD as well as WSL Ubuntu bash sehll.

![image](https://user-images.githubusercontent.com/1575051/60687469-cdf48c00-9e7c-11e9-9bb7-34cfd48165dc.png)

**Comment by cdalexndr** [comment]
So the problem is in my environment. 
These are my global installed npm packages, dunno if they may be conflicting somehow with this plugin:
```
> npm list -g --depth=0
+-- bower@1.8.2
+-- dependency-cruiser@4.25.0
+-- jscs@3.0.7
+-- npm@6.10.0
+-- rollup@1.16.4
+-- terser@4.0.2
`-- typescript@3.5.2
```
npm v6.10.0

**Comment by cdalexndr** [comment]
The problem was the old node version v6.5.0, updated to v10.16.0 and now it works.

**Comment by kevinkace** [comment]
Might be good to add this to the readme.

**Comment by Garfield550** [comment]
No output use `rollup` 2.3.1 and `rollup-plugin-analyzer` 3.2.2.

I run `rollup` command with both PowerShell Core(my login shell) and ZShell(iTerm 2 profile).

Full terminal log: 
```shell
~/Projects/GitHub/taro-ui [ui-next ≡ +1 ~4 -0 !]> yarn rollup --config ./config/rollup.config.js
yarn run v1.22.4
$ /Users/<Name>/Projects/GitHub/taro-ui/node_modules/.bin/rollup --config ./config/rollup.config.js

/Users/<Name>/Projects/GitHub/taro-ui/src/index.ts → dist/index.js, dist/es/index.js, dist/umd/index.js...
created dist/index.js, dist/es/index.js, dist/umd/index.js in 56.9s
✨  Done in 58.91s.
```

My `rollup.config.js` file:

```js
import NodePath from 'path'
import RollupJson from '@rollup/plugin-json'
import RollupNodeResolve from '@rollup/plugin-node-resolve'
import RollupCommonjs from '@rollup/plugin-commonjs'
import RollupTypescript from 'rollup-plugin-typescript2'
import RollupAnalyze from 'rollup-plugin-analyzer'
import Package from '../package.json'

const resolveFile = path => NodePath.resolve(__dirname, '..', path)

const externalPackages = [
  'react',
  'react-dom',
  '@tarojs/components',
  '@tarojs/runtime',
  '@tarojs/taro',
  '@tarojs/react'
]

export default {
  input: resolveFile(Package.source),
  output: [
    {
      file: resolveFile(Package.main),
      format: 'cjs'
    },
    {
      file: resolveFile(Package.module),
      format: 'es'
    },
    {
      file: resolveFile(Package.browser),
      format: 'umd',
      name: 'taro-ui',
      globals: {
        react: 'React',
        '@tarojs/components': 'components',
        '@tarojs/taro': 'Taro'
      }
    }
  ],
  external: externalPackages,
  plugins: [
    RollupJson(),
    RollupNodeResolve({
      customResolveOptions: {
        moduleDirectory: 'node_modules'
      }
    }),
    RollupCommonjs(),
    RollupTypescript({
      tsconfig: resolveFile('tsconfig.build.json')
    }),
    RollupAnalyze({ skipFormatted: true })
  ]
}
```

System environments:

OS: macOS 10.15.3 (19D76)
PowerShell: 7.0.0
zsh: 5.7.1 (x86_64-apple-darwin19.0)
Node: 13.11.0
npm: 6.13.7
yarn: 1.22.4
rollup: 2.3.1
rollup-plugin-analyzer: 3.2.2
