### ISSUE TITLE
Meaning of `Rendered size`

### ISSUE THREAD

**Issue by lufego** [doesdev/rollup-plugin-analyzer#14]
Hello, I'd like to know what exactly "rendered size" means? Is it about the parsed size (the actual compiled bundle files / size after minification) or gzipped?

```js 
----------------------------- Rollup File Analysis ----------------------------- bundle size: 123.56 KB original size: 165.637 KB code reduction: 25.4 % module count: 22
█████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
file: /node_modules/lit-element/lib/updating-element.js
bundle space: 19 %
rendered size: 23.472 KB
original size: 25.603 KB
code reduction: 8.32 %
dependents: 1

```

Thanks in advance

**Comment by doesdev** [comment]
It's the size of what's left after tree-shaking and before any other processing like minification and compression. It is taken from the values produced by Rollup for `renderedLength`. 

You can see it noted as a comment in the API options object [here](https://rollupjs.org/guide/en/#javascript-api).

I'm going to close this but feel free to reply back if any further clarification is needed.
