### ISSUE TITLE
Doesn't work when emitting assets

### ISSUE THREAD

**Issue by edoardocavazza** [doesdev/rollup-plugin-analyzer#15]
It seems that this plugin throws in the `generateBundle` hook when the `bundle` refers to an asset emitted by the bundle, because `bundleMods` is `undefined`:
```
TypeError: Cannot convert undefined or null to object
```

**Comment by doesdev** [comment]
Sorry for the delay, gonna try and check this out tonight. Thanks for reporting.

**Comment by doesdev** [comment]
Well, 3.2.2 addresses the stated exception. It is however a very surface level resolution and may not truly fix the problem. That is, it only serves to prevent the exception and doesn't address the specific use case.

If that doesn't provide the expected output please reply with a basic repro and I'll try to ensure the use case is fully addressed.
