### ISSUE TITLE
NPM Script Analyze only

### ISSUE THREAD

**Issue by aress31** [doesdev/rollup-plugin-analyzer#18]
Could you please document how to add an `analyze` only npm script to check the bundles size without having to build the entire project?

What would the NPM script look like?
```json
{
analyzer: "something -c something else"
}
```

**Comment by doesdev** [comment]
Unfortunately you wouldn't be able to get an analysis without a full build. I thought there might be a way to redirect the build output to dev/null but after playing around with Rollup's CLI options for a bit I've not found a way to do it. You could potentially create a separate Rollup config something like `rollup.ananlyze.config.js` that outputs to a directory and then removes the output when the build completes. But that is probably beyond the point of diminishing returns. 

Unfortunately I don't have a good solution for this one. Even if you did decide to go the separate config route it will still take the same amount of time as a full build so not much would be gained there. 

I'm going to close this but feel free to re-open if you have any other ideas on how it might be accomplished.

**Comment by aress31** [comment]
@doesdev thanks for this detailed explanation, unfortunately, I am a total rookie and that's why I opened this ticket to get instructions on how to achieve the above. 

Why not keeping the ticket open and label it with help wanted?

**Comment by doesdev** [comment]
No problem, I'm glad to provide the explanation. 

If there were a way to accomplish it without needing to  do the full build I would definitely keep it open, as that would be awesome to have. Unfortunately though the information the plugin uses to build the analysis is emitted by Rollup during the build process, so there wouldn't be way to do that.

If you do think it's helpful to have a special config for that you can drop in a copy of your current config and I'll detail what you would need to do to make that work. I'm just thinking the value in such a thing would be not having to wait for a full build to get the analysis and unfortunately that one isn't doable.

**Comment by aress31** [comment]
I agree with you if the entire building process is need I might as well just keep it as it is and build it whilst analysing. Hopefully, other people can bring in ideas in this ticket.
