### ISSUE TITLE
What is hideDeps doing?

### ISSUE THREAD

**Issue by incorrupt** [doesdev/rollup-plugin-analyzer#20]
I am bundling some small `node_modules` dependencies with Rollup. I would think `hideDeps` would hide those from the output but it's not the case.

1. What is `hideDeps` for?
2. How to hide all outputs from `node_modules`?

**Comment by doesdev** [comment]
Hey, thanks for dropping those questions here as well as the input on the `filter` option. Will follow up on that later (need to think some more on it).

1. If enabled dependents won't be itemized. An example would probably be most useful, see below
2. `{ filter: (m) => !m.id.match('node_modules'), filterSummary: true }` (just released in v3.3.0)

#### With `hideDeps === false`
```sh
█████████████████████████████████████████████░░░░░
file:            /test/_fixtures/virtual-insanity.js
bundle space:    90.64 %
rendered size:   2.546 KB
original size:   2.57 KB
code reduction:  0.93 %
dependents:      1
  - /test/_fixtures/jamiroquai.js
```

#### With `hideDeps === true`
```sh
█████████████████████████████████████████████░░░░░
file:            /test/_fixtures/virtual-insanity.js
bundle space:    90.64 %
rendered size:   2.546 KB
original size:   2.57 KB
code reduction:  0.93 %
dependents:      1
```
